//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Higo.CharacterController.Generated
{
    [BurstCompile]
    public struct CharacterControllerTransformGhostComponentSerializer
    {
        static GhostComponentSerializer.State GetState()
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds due to TYpeManager not being initialized yet
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 4379934046830037180,
                    ExcludeFromComponentCollectionHash = 0,
                    ComponentType = ComponentType.ReadWrite<CharacterControllerTransform>(),
                    ComponentSize = UnsafeUtility.SizeOf<CharacterControllerTransform>(),
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                    ChangeMaskBits = ChangeMaskBits,
                    SendMask = GhostComponentSerializer.SendMask.Predicted,
                    SendToOwner = SendToOwnerType.All,
                    SendForChildEntities = 1,
                    VariantHash = 0,
                    CopyToSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                    CopyFromSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                    RestoreFromBackup =
                        new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                    PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                    CalculateChangeMask =
                        new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                            CalculateChangeMask),
                    Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                    Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                    #if UNITY_EDITOR || DEVELOPMENT_BUILD
                    ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                    #endif
                };
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                s_State.NumPredictionErrorNames = GetPredictionErrorNames(ref s_State.PredictionErrorNames);
                #endif
                s_StateInitialized = true;
            }
            return s_State;
        }
        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;
        public static GhostComponentSerializer.State State => GetState();
        public struct Snapshot
        {
            public float Value_rotX;
            public float Value_rotY;
            public float Value_rotZ;
            public float Value_rotW;
            public float Value_pos_x;
            public float Value_pos_y;
            public float Value_pos_z;
        }
        public const int ChangeMaskBits = 2;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.Value_rotX = component.Value.rot.value.x;
                snapshot.Value_rotY = component.Value.rot.value.y;
                snapshot.Value_rotZ = component.Value.rot.value.z;
                snapshot.Value_rotW = component.Value.rot.value.w;
                snapshot.Value_pos_x = component.Value.pos.x;
                snapshot.Value_pos_y = component.Value.pos.y;
                snapshot.Value_pos_z = component.Value.pos.z;
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                //Compute the required owner mask for the components and buffers by retrievieng the ghost owner id from the data for the current tick.
                if (snapshotInterpolationData.GhostOwner > 0)
                {
                    var requiredOwnerMask = snapshotInterpolationData.GhostOwner == deserializerState.GhostOwner
                        ? SendToOwnerType.SendToOwner
                        : SendToOwnerType.SendToNonOwner;
                    if ((deserializerState.SendToOwner & requiredOwnerMask) == 0)
                        continue;
                }
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                float snapshotInterpolationFactorRaw = snapshotInterpolationData.InterpolationFactor;
                float snapshotInterpolationFactor = snapshotInterpolationFactorRaw;
                ref var component = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(componentData, componentStride*i);
                component.Value.rot = new quaternion(snapshotBefore.Value_rotX, snapshotBefore.Value_rotY, snapshotBefore.Value_rotZ, snapshotBefore.Value_rotW);
                component.Value.pos = new float3(snapshotBefore.Value_pos_x, snapshotBefore.Value_pos_y, snapshotBefore.Value_pos_z);

            }
        }


        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(backupData, 0);
            component.Value.rot = backup.Value.rot;
            component.Value.pos.x = backup.Value.pos.x;
            component.Value.pos.y = backup.Value.pos.y;
            component.Value.pos.z = backup.Value.pos.z;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.Value_rotX != baseline.Value_rotX ||
                        snapshot.Value_rotY != baseline.Value_rotY ||
                        snapshot.Value_rotZ != baseline.Value_rotZ ||
                        snapshot.Value_rotW != baseline.Value_rotW) ? 1u : 0;
            changeMask |= (snapshot.Value_pos_x != baseline.Value_pos_x) ? (1u<<1) : 0;
            changeMask |= (snapshot.Value_pos_y != baseline.Value_pos_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.Value_pos_z != baseline.Value_pos_z) ? (1u<<1) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 2);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
            {
                writer.WritePackedFloatDelta(snapshot.Value_rotX, baseline.Value_rotX, compressionModel);
                writer.WritePackedFloatDelta(snapshot.Value_rotY, baseline.Value_rotY, compressionModel);
                writer.WritePackedFloatDelta(snapshot.Value_rotZ, baseline.Value_rotZ, compressionModel);
                writer.WritePackedFloatDelta(snapshot.Value_rotW, baseline.Value_rotW, compressionModel);
            }
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.Value_pos_x, baseline.Value_pos_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.Value_pos_y, baseline.Value_pos_y, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.Value_pos_z, baseline.Value_pos_z, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
            {
                snapshot.Value_rotX = reader.ReadPackedFloatDelta(baseline.Value_rotX, compressionModel);
                snapshot.Value_rotY = reader.ReadPackedFloatDelta(baseline.Value_rotY, compressionModel);
                snapshot.Value_rotZ = reader.ReadPackedFloatDelta(baseline.Value_rotZ, compressionModel);
                snapshot.Value_rotW = reader.ReadPackedFloatDelta(baseline.Value_rotW, compressionModel);
            }
            else
            {
                snapshot.Value_rotX = baseline.Value_rotX;
                snapshot.Value_rotY = baseline.Value_rotY;
                snapshot.Value_rotZ = baseline.Value_rotZ;
                snapshot.Value_rotW = baseline.Value_rotW;
            }
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Value_pos_x = reader.ReadPackedFloatDelta(baseline.Value_pos_x, compressionModel);
            else
                snapshot.Value_pos_x = baseline.Value_pos_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Value_pos_y = reader.ReadPackedFloatDelta(baseline.Value_pos_y, compressionModel);
            else
                snapshot.Value_pos_y = baseline.Value_pos_y;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.Value_pos_z = reader.ReadPackedFloatDelta(baseline.Value_pos_z, compressionModel);
            else
                snapshot.Value_pos_z = baseline.Value_pos_z;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<CharacterControllerTransform>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.Value.rot.value, backup.Value.rot.value));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.Value.pos, backup.Value.pos));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("Value.rot"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("Value.pos"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}
